### PR TITLE
Small bug fixes and localization of textSetting

### PR DESCRIPTION
**Pull request by lukhong**
Bug fixes for two issues.
https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/issues/122
https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/issues/123

Improvement to allow the localization of `textSetting`
https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/issues/125

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **[CONTRIBUTING](/CONTRIBUTING.md)** document
- [ ] My code follows the code style of this project (hint: install an [xo editor plugin](https://github.com/xojs/xo#editor-plugins))
- [ ] Any required documentation has been added
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by rossiam** [comment]
It looks like you have a new dependency on the underscore library but no changes to package.json and package-lock.json. Be sure to do a `--save` when you `npm install` (i.e. `npm install --save underscore` and then commit package.json and package-lock.json.

**Comment by rossiam** [comment]
Don't forget to also include package-lock.json. There were some other commits to that one so you might have to deal with some conflicts.

**Comment by lukhong** [comment]
@rossiam Thanks for the comments, I updated related `.json` files. Please review them.

**Comment by bflorian** [comment]
@rossiam @lukhong this change breaks text fields that aren't required and have no default value. In those cases the value of the field gets set to the default i18n key, for example with a input defined as:
```
section.textSetting('cameraPatToken').required(false);
```
Not entering anything results in a value of `pages.mainPage.settings.cameraPatToken.defaultValue`

image

**Comment by lukhong** [comment]
@bflorian Yes, that is true and I tried to find a way to handle it nicely but couldn't. However, I thought we can avoid showing like above by giving an empty string to `defaltValue` like `.defaultValye('')`. That is the same way we are already doing to the `descrption`. How do you think about it?

**Comment by bflorian** [comment]
@lukhong I think a text field should continue to have a default value only if one is explicitly set. As currently implemented this is a breaking change. I also don't think the standard behavior should be to pass default values through localization, though I can see the value of that in some cases.  So how about something like this:
```
section.textSetting('cameraToken')  // field defaults to blank

section.textSetting('cameraToken')  // field defaults to 'XXXX'
    .defaultValue('XXXX')

section.textSetting('cameraToken')  // default value is translated from the i18n key
    .translatedDefaultValue()
```

**Pull request merged**
